export const RECIPES = [
  {
    id: "planks-from-wood",
    name: "Planks",
    ingredients: { wood: 1 },
    output: "planks",
    amount: 4,
    category: "materials",
  },
  {
    id: "sticks-from-planks",
    name: "Sticks",
    ingredients: { planks: 2 },
    output: "sticks",
    amount: 4,
    category: "materials",
  },
  {
    id: "wood-wall-from-planks",
    name: "Wood Wall",
    ingredients: { planks: 1 },
    output: "woodWall",
    amount: 4,
    category: "walls",
  },
  {
    id: "wood-wall-from-wood",
    name: "Wood Wall",
    ingredients: { wood: 1 },
    output: "woodWall",
    amount: 2,
    category: "walls",
  },
  {
    id: "stone-wall",
    name: "Stone Wall",
    ingredients: { stone: 1 },
    output: "stoneWall",
    amount: 4,
    category: "walls",
  },
  {
    id: "brick-wall",
    name: "Brick Wall",
    ingredients: { brick: 1 },
    output: "brickWall",
    amount: 4,
    category: "walls",
  },
  {
    id: "glass-wall",
    name: "Glass Wall",
    ingredients: { glass: 1 },
    output: "glassWall",
    amount: 4,
    category: "walls",
  },
  {
    id: "torch-from-coal",
    name: "Torch",
    ingredients: { sticks: 1, coal: 1 },
    output: "torch",
    amount: 4,
    category: "utility",
  },
  {
    id: "torch-from-wood",
    name: "Torch",
    ingredients: { sticks: 1, wood: 1 },
    output: "torch",
    amount: 2,
    category: "utility",
  },
  {
    id: "wooden-pickaxe",
    name: "Wooden Pickaxe",
    ingredients: { planks: 3, sticks: 2 },
    output: "woodenPickaxe",
    amount: 1,
    category: "tools",
  },
  {
    id: "wooden-axe",
    name: "Wooden Axe",
    ingredients: { planks: 3, sticks: 2 },
    output: "woodenAxe",
    amount: 1,
    category: "tools",
  },
  {
    id: "wooden-shovel",
    name: "Wooden Shovel",
    ingredients: { planks: 1, sticks: 2 },
    output: "woodenShovel",
    amount: 1,
    category: "tools",
  },
  {
    id: "stone-pickaxe",
    name: "Stone Pickaxe",
    ingredients: { stone: 3, sticks: 2 },
    output: "stonePickaxe",
    amount: 1,
    category: "tools",
  },
  {
    id: "stone-axe",
    name: "Stone Axe",
    ingredients: { stone: 3, sticks: 2 },
    output: "stoneAxe",
    amount: 1,
    category: "tools",
  },
  {
    id: "stone-shovel",
    name: "Stone Shovel",
    ingredients: { stone: 1, sticks: 2 },
    output: "stoneShovel",
    amount: 1,
    category: "tools",
  },
  {
    id: "workbench-from-planks",
    name: "Workbench",
    ingredients: { planks: 4 },
    output: "workbench",
    amount: 1,
    category: "utility",
  },
  {
    id: "workbench-from-wood",
    name: "Workbench",
    ingredients: { wood: 2 },
    output: "workbench",
    amount: 1,
    category: "utility",
  },
  {
    id: "ladder-from-wood",
    name: "Ladder",
    ingredients: { sticks: 2, wood: 1 },
    output: "ladder",
    amount: 3,
    category: "utility",
  },
  {
    id: "ladder-from-planks",
    name: "Ladder",
    ingredients: { sticks: 2, planks: 1 },
    output: "ladder",
    amount: 3,
    category: "utility",
  },
];
