export const RECIPES = [
  {
    id: "planks-from-wood",
    name: "Planks",
    size: "2x2",
    pattern: ["W"],
    key: { W: "wood" },
    output: "planks",
    amount: 4,
  },
  {
    id: "sticks-from-planks",
    name: "Sticks",
    size: "2x2",
    pattern: ["P", "P"],
    key: { P: "planks" },
    output: "sticks",
    amount: 4,
  },
  {
    id: "torch-from-coal",
    name: "Torch",
    size: "2x2",
    pattern: ["C", "S"],
    key: { C: "coal", S: "sticks" },
    output: "torch",
    amount: 4,
  },
  {
    id: "torch-from-wood",
    name: "Torch",
    size: "2x2",
    pattern: ["W", "S"],
    key: { W: "wood", S: "sticks" },
    output: "torch",
    amount: 2,
  },
  {
    id: "workbench-from-planks",
    name: "Workbench",
    size: "2x2",
    pattern: ["PP", "PP"],
    key: { P: "planks" },
    output: "workbench",
    amount: 1,
  },
  {
    id: "wood-wall",
    name: "Wood Wall",
    size: "3x3",
    pattern: ["PPP", "PPP"],
    key: { P: "planks" },
    output: "woodWall",
    amount: 6,
    station: "workbench",
  },
  {
    id: "stone-wall",
    name: "Stone Wall",
    size: "3x3",
    pattern: ["SSS", "SSS"],
    key: { S: "stone" },
    output: "stoneWall",
    amount: 6,
    station: "workbench",
  },
  {
    id: "brick-wall",
    name: "Brick Wall",
    size: "3x3",
    pattern: ["BBB", "BBB"],
    key: { B: "brick" },
    output: "brickWall",
    amount: 6,
    station: "workbench",
  },
  {
    id: "glass-wall",
    name: "Glass Wall",
    size: "3x3",
    pattern: ["GGG", "GGG"],
    key: { G: "glass" },
    output: "glassWall",
    amount: 6,
    station: "workbench",
  },
  {
    id: "ladder",
    name: "Ladder",
    size: "3x3",
    pattern: ["S S", "SSS", "S S"],
    key: { S: "sticks" },
    output: "ladder",
    amount: 3,
    station: "workbench",
  },
  {
    id: "wooden-pickaxe",
    name: "Wooden Pickaxe",
    size: "3x3",
    pattern: ["PPP", " S ", " S "],
    key: { P: "planks", S: "sticks" },
    output: "woodenPickaxe",
    amount: 1,
    station: "workbench",
  },
  {
    id: "wooden-axe",
    name: "Wooden Axe",
    size: "3x3",
    pattern: ["PP ", "PS ", " S "],
    key: { P: "planks", S: "sticks" },
    output: "woodenAxe",
    amount: 1,
    station: "workbench",
    mirror: true,
  },
  {
    id: "wooden-shovel",
    name: "Wooden Shovel",
    size: "3x3",
    pattern: [" P ", " S ", " S "],
    key: { P: "planks", S: "sticks" },
    output: "woodenShovel",
    amount: 1,
    station: "workbench",
  },
  {
    id: "stone-pickaxe",
    name: "Stone Pickaxe",
    size: "3x3",
    pattern: ["SSS", " T ", " T "],
    key: { S: "stone", T: "sticks" },
    output: "stonePickaxe",
    amount: 1,
    station: "workbench",
  },
  {
    id: "stone-axe",
    name: "Stone Axe",
    size: "3x3",
    pattern: ["SS ", "ST ", " T "],
    key: { S: "stone", T: "sticks" },
    output: "stoneAxe",
    amount: 1,
    station: "workbench",
    mirror: true,
  },
  {
    id: "stone-shovel",
    name: "Stone Shovel",
    size: "3x3",
    pattern: [" S ", " T ", " T "],
    key: { S: "stone", T: "sticks" },
    output: "stoneShovel",
    amount: 1,
    station: "workbench",
  },
];
